### ISSUE TITLE
`comm.Scatter` NumPy type hint warnings

### ISSUE THREAD

**Issue by MaximilienLC** [mpi4py/mpi4py#435]
Getting type hints warnings (incompatible type `sendbuf` & `recvbuf`) for `mpi4py@master` for the NumPy Scatter example (https://mpi4py.readthedocs.io/en/stable/tutorial.html) which do not appear for `mpi4py@3.1.5`. Were NumPy arrays inadvertently removed from the list of supported type hints?

The same might be true for operations like `comm.Gather`.

**Comment by dalcinl** [comment]
Please provide a proper self-contained reproducer example, the exact errors you get, and info about package versions (numpy, mypy, etc.).

**Comment by MaximilienLC** [comment]
numpy==1.26.2
mypy==1.7.0
```
from mpi4py import MPI
import numpy as np

comm = MPI.COMM_WORLD
size = comm.Get_size()
rank = comm.Get_rank()

sendbuf = None
if rank == 0:
    sendbuf = np.empty([size, 100], dtype='i')
    sendbuf.T[:,:] = range(size)
recvbuf = np.empty(100, dtype='i')
comm.Scatter(sendbuf, recvbuf, root=0)
assert np.allclose(recvbuf, rank)
```

`Argument 1 to "Scatter" of "Comm" has incompatible type "ndarray[Any, dtype[Any]] | None"; expected "SupportsBuffer | SupportsDLPack | SupportsCAI | tuple[SupportsBuffer | SupportsDLPack | SupportsCAI, Integral] | tuple[SupportsBuffer | SupportsDLPack | SupportsCAI, Datatype | str] | tuple[SupportsBuffer | SupportsDLPack | SupportsCAI, Integral, Datatype | str] | list[Any] | None"  [arg-type] mypy`

`Argument 2 to "Scatter" of "Comm" has incompatible type "ndarray[Any, dtype[Any]]"; expected "SupportsBuffer | SupportsDLPack | SupportsCAI | tuple[SupportsBuffer | SupportsDLPack | SupportsCAI, Integral] | tuple[SupportsBuffer | SupportsDLPack | SupportsCAI, Datatype | str] | tuple[SupportsBuffer | SupportsDLPack | SupportsCAI, Integral, Datatype | str] | tuple[BottomType | None, Integral, Datatype] | list[Any] | InPlaceType | None"  [arg-type] mypy`

**Comment by dalcinl** [comment]
I see what's going on... in the last release 3.1.5, mpi4py had a type alias `Buffer = Any` that would basically accept anything as a buffer-like object. The reason for that was the absolute lack of a proper way to do typing for the Python buffer interface. That changed in Python 3.12. Now mpi4py@master does the proper thing, and defines a `SupportsBuffer` protocol with the `__buffer__` special method. But NumPy defines the special method only for py >= 3.12 [[link]](https://github.com/numpy/numpy/blob/v1.26.2/numpy/__init__.pyi#L1518), so if you are typing with a previous version of Python, things do not work properly. I do not know what's the proper way to do things for all versions of Python.

**Comment by dalcinl** [comment]
@MaximilienLC Could you please try the `typing/buffer` branch I just pushed? The fix is kind of cheating: I'm defining `SupportsBuffer` as a type alias for `Any` for Py<3.12. I did some research to come up with a better fix, but there are issues/oddities/mismatches in both mypy/typing_extensions/typeshed/numpy that prevent a proper fix to work from mpi4py's side. I honestly do not have the energy to submit and followup issues on each individual project.

PS: It would be great if you could test both Python 3.11 and Python 3.12. I'm a little bit short of time right now.

**Comment by MaximilienLC** [comment]
Hey Lisandro, I'm also a bit short on time so sorry it's not exactly what you asked for but I tested for Python 3.10 and mypy now stays quiet. I also tested the main branch from 2 weeks ago and the error is still there.
