### ISSUE TITLE
testPackUnpackExternal (and testArgsOnlyAtRoot) fails with mpich on 32-bit arches

### ISSUE THREAD

**Issue by drew-parsons** [mpi4py/mpi4py#514]
Debian is moving to OpenMPI 5 as default MPI.  But OpenMPI 5 no longer supports 32-bit architectures.  Therefore we have started using mpich as the default MPI on 32-bit architectures.  Current mpich is 4.2.0.

However, the testPackUnpackExternal is failing on some 32-bit arches
armel: https://buildd.debian.org/status/fetch.php?pkg=mpi4py&arch=armel&ver=3.1.6-1%2Bb1&stamp=1720630197&raw=0
armhf: https://buildd.debian.org/status/fetch.php?pkg=mpi4py&arch=armhf&ver=3.1.6-1%2Bb1&stamp=1720629854&raw=0
hppa: https://buildd.debian.org/status/fetch.php?pkg=mpi4py&arch=hppa&ver=3.1.6-1%2Bb1&stamp=1720632444&raw=0

powerpc fails with  a different error in testArgsOnlyAtRoot, https://buildd.debian.org/status/fetch.php?pkg=mpi4py&arch=powerpc&ver=3.1.6-1%2Bb1&stamp=1720631261&raw=0

i386, m68k and sh4 pass. All build logs can be found at  https://buildd.debian.org/status/package.php?p=mpi4py

The error on 32-bit ARM and hppa is
```
testPackUnpackExternal (test_pack.TestPackExternal.testPackUnpackExternal) ... Conversion of types whose size is not the same as the size in external32 is not supported
Aborting with internal error
[unset]: PMIU_write error; fd=-1 buf=:cmd=abort exitcode=1 message=Aborting with internal error
:
system msg for write_line failure : Bad file descriptor
```

The error on powerpc is 
```
testArgsOnlyAtRoot (test_spawn.TestSpawnSelf.testArgsOnlyAtRoot) ... [mpiexec@debian-project-be-1] handle_pmi_cmd (mpiexec/pmiserv_cb.c:57): unable to parse PMI command
[mpiexec@debian-project-be-1] control_cb (mpiexec/pmiserv_cb.c:367): unable to process PMI command
[mpiexec@debian-project-be-1] HYDT_dmxu_poll_wait_for_event (lib/tools/demux/demux_poll.c:76): callback returned error status
[mpiexec@debian-project-be-1] HYD_pmci_wait_for_completion (mpiexec/pmiserv_pmci.c:173): error waiting for event
[mpiexec@debian-project-be-1] main (mpiexec/mpiexec.c:260): process manager error waiting for completion
```

What's the best way to proceed?

**Comment by dalcinl** [comment]
> testPackUnpackExternal (test_pack.TestPackExternal.testPackUnpackExternal) ... Conversion of types whose size is not the same as the size in external32 is not supported

Well, maybe this is something that we could somehow workaround in mpi4py testsuite, skipping tests for datatypes not satisfying the condition.

> The error on powerpc is
> 
> ```
> testArgsOnlyAtRoot (test_spawn.TestSpawnSelf.testArgsOnlyAtRoot)
> ```

This one is really weird, as there is only one process in `COMM_SELF`.  Although the failure may be triggered from previous tests. 

I think these issues should be reported upstream to MPICH. In the meantime, I guess your only option is to patch and skip that test.

**Comment by drew-parsons** [comment]
Thanks.  I'll skip them as a workaround for the time being.

**Comment by dalcinl** [comment]
@hzhou FYI. I'm a bit puzzled by the spawn failures, I don't see how they may fail in some but not all 32bit architectures.

**Comment by hzhou** [comment]
> > testPackUnpackExternal (test_pack.TestPackExternal.testPackUnpackExternal) ... Conversion of types whose size is not the same as the size in external32 is not supported
> 
> Well, maybe this is something that we could somehow workaround in mpi4py testsuite, skipping tests for datatypes not satisfying the condition.

Which type is that? Is it `long double`?

> testArgsOnlyAtRoot (test_spawn.TestSpawnSelf.testArgsOnlyAtRoot)

Have to debug it to know for sure. Is it reproducible? If it is, try run it with `mpiexec -v ...`

**Comment by dalcinl** [comment]
> Which type is that? Is it `long double`?

We are not sure. For the time being, I did a manual test in a docker container running `podman run -it --rm --platform linux/armel debian:12` and then installing everything by hand (IIRC, MPICH was 4.0.2, but I may be wrong). The mpi4py external32 pack/unpack tests failed at `MPI_DOUBLE` (!?) with "Bus error", which is really weird.

> If it is, try run it with `mpiexec -v ...`

@drew-parsons Maybe you can give quick try to Hui's suggestion?

**Comment by drew-parsons** [comment]
After skipping testPackUnpackExternal, 32-bit arm (mpich) is triggering the spawn failures too. 

One after another, each of testArgsOnlyAtRoot, testArgsOnlyAtRootMultiple, testCommSpawn, testCommSpawnMultiple fails with the PMI error.  I guess the entire BaseTestSpawn class is compromised.

I activated `mpirun -v`, but it's not giving extra information.

New armel log: https://buildd.debian.org/status/fetch.php?pkg=mpi4py&arch=armel&ver=3.1.6-4&stamp=1720738780&raw=0

**Comment by drew-parsons** [comment]
For what it's worth, h5py gets an mpich PMI error too on i386, https://buildd.debian.org/status/fetch.php?pkg=h5py&arch=i386&ver=3.11.0-2%2Bb2&stamp=1720737972&raw=0

I'm wondering if this upstream mpich issue and patch is relevant (applied to mpich 4.2.2, so not in debian yet)
https://github.com/pmodels/mpich/issues/6946
https://github.com/pmodels/mpich/pull/7000

**Comment by dalcinl** [comment]
I tested mpi4py@master using docker under emulation and the spawn tests seem to be OK:

```
podman run -it --rm --platform linux/arm/v5 debian:unstable

apt update
apt install -y libmpich-dev python3-dev python3-setuptools git
git clone https://github.com/mpi4py/mpi4py.git
cd mpi4py
CFLAGS=-O0 make py=3
export PYTHONPATH=$PWD/src
python test/test_spawn.py
mpiexec -n 5 python test/test_spawn.py
```

Running against mpi4py@3.1.6 reproduces the issue. I'm not sure what's going on. I don't recall any fundamental change or bugfix in mpi4py that would justify such behavior. 

@drew-parsons As we are very close to release mpi4py 4.0.0, I would suggest to move on and just add the skip decorator to all spawn tests (in the topmost base class).

**Comment by drew-parsons** [comment]
Next failure happens in test_exceptions.TestExcErrhandlerNull.  Only these (3) left, others pass.
https://buildd.debian.org/status/fetch.php?pkg=mpi4py&arch=armel&ver=3.1.6-5&stamp=1720786554&raw=0
```
FAIL: testCommSelfSetErrhandler (test_exceptions.TestExcErrhandlerNull.testCommSelfSetErrhandler)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/test/mpiunittest.py", line 13, in assertRaisesMPI
    callableObj(*args, **kwargs)
  File "mpi4py/MPI/Comm.pyx", line 1336, in mpi4py.MPI.Comm.Set_errhandler
mpi4py.MPI.Exception: Invalid errhandler, error stack:
internal_Comm_set_errhandler(41812): MPI_Comm_set_errhandler(MPI_COMM_SELF, MPI_ERRHANDLER_NULL) failed
internal_Comm_set_errhandler(41771): Null errhandler 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/test/test_exceptions.py", line 352, in testCommSelfSetErrhandler
    self.assertRaisesMPI(
  File "/<<PKGBUILDDIR>>/test/mpiunittest.py", line 30, in assertRaisesMPI
    raise self.failureException(
AssertionError: generated error class is '<unknown>' (80), but expected 'ERR_ARG' (12)

======================================================================
FAIL: testCommWorldSetErrhandler (test_exceptions.TestExcErrhandlerNull.testCommWorldSetErrhandler)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/test/mpiunittest.py", line 13, in assertRaisesMPI
    callableObj(*args, **kwargs)
  File "mpi4py/MPI/Comm.pyx", line 1336, in mpi4py.MPI.Comm.Set_errhandler
mpi4py.MPI.Exception: Invalid errhandler, error stack:
internal_Comm_set_errhandler(41812): MPI_Comm_set_errhandler(MPI_COMM_WORLD, MPI_ERRHANDLER_NULL) failed
internal_Comm_set_errhandler(41771): Null errhandler 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/test/test_exceptions.py", line 356, in testCommWorldSetErrhandler
    self.assertRaisesMPI(
  File "/<<PKGBUILDDIR>>/test/mpiunittest.py", line 30, in assertRaisesMPI
    raise self.failureException(
AssertionError: generated error class is '<unknown>' (80), but expected 'ERR_ARG' (12)

======================================================================
FAIL: testFree (test_exceptions.TestExcErrhandlerNull.testFree)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/test/mpiunittest.py", line 13, in assertRaisesMPI
    callableObj(*args, **kwargs)
  File "mpi4py/MPI/Errhandler.pyx", line 32, in mpi4py.MPI.Errhandler.Free
mpi4py.MPI.Exception: Invalid errhandler, error stack:
internal_Errhandler_free(41924): MPI_Errhandler_free(errhandler=0xf63af538) failed
internal_Errhandler_free(41887): Null errhandler 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/test/test_exceptions.py", line 349, in testFree
    self.assertRaisesMPI(MPI.ERR_ARG, MPI.ERRHANDLER_NULL.Free)
  File "/<<PKGBUILDDIR>>/test/mpiunittest.py", line 30, in assertRaisesMPI
    raise self.failureException(
AssertionError: generated error class is '<unknown>' (80), but expected 'ERR_ARG' (12)
```

**Comment by dalcinl** [comment]
> Next failure happens in test_exceptions.TestExcErrhandlerNull.

This one is expected, and the test code in mp4py 3.1.6 is not prepared to handle a new MPI error class introduced recently in MPI 4.1 and supported in MPICH since v4.2.

You'll have to either skip these failing tests, or patch them replacing the value `MPI.ERR_ARG` with the list `[MPI.ERR_ARG, 61]`, where `61` is just the hardwired value of `MPI_ERR_ERRHANDLER` from `mpi.h`.

**Comment by drew-parsons** [comment]
Just as easy to patch it as to skip it.  I'll give it a try

**Comment by drew-parsons** [comment]
Need to check those numbers.
mpich 4.2.0 shows 80 not 61,
/usr/lib/x86_64-linux-gnu/mpich/include/mpi.h
```
...
/* Return codes for functions in the MPI Tool Information Interface */
#define MPI_T_ERR_MEMORY            59  /* Out of memory */
#define MPI_T_ERR_NOT_INITIALIZED   60  /* Interface not initialized */
#define MPI_T_ERR_CANNOT_INIT       61  /* Interface not in the state to
                                           be initialized */
#define MPI_T_ERR_INVALID_INDEX     62  /* The index is invalid or
                                           has been deleted  */
...
#define MPI_T_ERR_NOT_SUPPORTED    78  /* Requested functionality not supported */
#define MPI_T_ERR_NOT_ACCESSIBLE   79  /* Requested functionality not accessible */

#define MPI_ERR_ERRHANDLER         80  /* Invalid errhandler handle */

#define MPI_ERR_LASTCODE    0x3fffffff  /* Last valid error code for a
                                           predefined error class */
#define MPICH_ERR_LAST_CLASS 80     /* It is also helpful to know the
                                       last valid class */
```

**Comment by dalcinl** [comment]
Sorry! Yes, the right value is `80`, I got confused with the value from a different header file related to the MPI ABI proposal.

**Comment by drew-parsons** [comment]
With testPackUnpackExternal and BaseTestSpawn skipped and TestExcErrhandlerNull patched, all 32-bit arches are building successfully now with mpich.  (Except hurd, it froze during tests)

**Comment by drew-parsons** [comment]
testPackUnpackExternal is failing on i386 in CI testing
https://ci.debian.net/packages/m/mpi4py/unstable/i386/49179799/

```
3175s testPackUnpackExternal (test_pack.TestPackExternal.testPackUnpackExternal) ... [proxy:0@ci-199-b75cface] Sending upstream hdr.cmd = CMD_STDERR
3175s ok
3175s [proxy:0@ci-199-b75cface] Sending upstream hdr.cmd = CMD_STDERR
3175s testPackUnpackExternal (test_pack.TestPackExternal.testPackUnpackExternal) ... [proxy:0@ci-199-b75cface] Sending upstream hdr.cmd = CMD_STDERR
3175s testPackSize (test_pack.TestPackExternal.testPackSize) ... [proxy:0@ci-199-b75cface] Sending upstream hdr.cmd = CMD_STDERR
3175s [proxy:0@ci-199-b75cface] Sending upstream hdr.cmd = CMD_STDERR
3175s ok
3175s testPackUnpackExternal (test_pack.TestPackExternal.testPackUnpackExternal) ... [proxy:0@ci-199-b75cface] Sending upstream hdr.cmd = CMD_STDERR
3175s ok
3175s testPackSize (test_pack.TestPackExternal.testPackSize) ... [proxy:0@ci-199-b75cface] Sending upstream hdr.cmd = CMD_STDERR
3175s [proxy:0@ci-199-b75cface] Sending upstream hdr.cmd = CMD_STDERR
3175s [proxy:0@ci-199-b75cface] Sending upstream hdr.cmd = CMD_STDERR
3175s ok
3175s testPackUnpackExternal (test_pack.TestPackExternal.testPackUnpackExternal) ... [proxy:0@ci-199-b75cface] Sending upstream hdr.cmd = CMD_STDERR
3175s Conversion of types whose size is not the same as the size in external32 is not supported
3175s [proxy:0@ci-199-b75cface] Sending upstream hdr.cmd = CMD_STDERR
3175s Conversion of types whose size is not the same as the size in external32 is not supported
3175s Aborting with internal error
3175s [proxy:0@ci-199-b75cface] Sending upstream hdr.cmd = CMD_STDERR
3175s [proxy:0@ci-199-b75cface] we don't understand this command, forwarding upstream
3175s [proxy:0@ci-199-b75cface]     cmd=abort exitcode=1 message=Aborting with internal error
3175s [proxy:0@ci-199-b75cface] Sending upstream hdr.cmd = CMD_PMI
3175s [mpiexec@ci-199-b75cface] [pgid: 0] got PMI command: cmd=abort exitcode=1 message=Aborting with internal error
```
Looking at the build log, https://buildd.debian.org/status/fetch.php?pkg=mpi4py&arch=i386&ver=3.1.6-6&stamp=1720950927&raw=0
it did fail during build tests but the failure didn't register to stop the build. I might need to fix that.
```
testPackSize (test_pack.TestPackExternal.testPackSize) ... ok
testPackUnpackExternal (test_pack.TestPackExternal.testPackUnpackExternal) ... Conversion of types whose size is not the same as the size in external32 is not supported
Aborting with internal error
[unset]: PMIU_write error; fd=-1 buf=:cmd=abort exitcode=1 message=Aborting with internal error
:
system msg for write_line failure : Bad file descriptor
I: running tests with MPI (5 processes)
```
As far as m68k and sh4 goes, they actually have build tests switched off (too many failures in general on these less common arches).  I think we can presume they would fail testPackUnpackExternal too.

**Comment by drew-parsons** [comment]
And (as expected) TestSpawnSelf then fails on i386 too. Consistent behaviour across all the 32-bit arches.

**Comment by dalcinl** [comment]
@drew-parsons Let's go one by one... 

I'm running tests with mpi4py@master and debian:unstable in a podman container

1. Now I can reproduce the pack/unpack external32, I forgot I have to install NumPy for full testing. Tests seem to fail for `long double [complex]` datatypes. The error message makes sense, as `sizeof(long double)` is 12 bytes on i386, and 16 bytes on external32. However, the support for external32 long double on 64bit may still be broken, because IIUC a `long double` in `external32` must be stored in IEEE quad-precision representation (GCC's `__float128`), and I don't think MPICH is doing that. Long story short, I'll push the following patch to mpi4py@master:
```diff
diff --git a/test/test_pack.py b/test/test_pack.py
index 811ad6b6..b05533c0 100644
--- a/test/test_pack.py
+++ b/test/test_pack.py
@@ -139,6 +139,8 @@ name, version = MPI.get_vendor()
 if name == 'MPICH':
     if version < (4, 0, 0):
         BaseTestPackExternal.skipdtype += 'ldgLFDG'
+    if platform.architecture()[0] == '32bit':
+        BaseTestPackExternal.skipdtype += 'gG'
 elif name == 'Open MPI':
     if version < (5, 0, 0):
         BaseTestPackExternal.skipdtype += 'gG'
```

2. Regarding the spawn tests, everything seems to work just fine on my local testing under the podman container engine. Any change that the issue is somehow related to network configuration on the Debian build hosts?
Maybe setting env vars `HYDRA_IFACE=lo` `HYDRA_LAUNCHER=fork`  would help? Perhaps things are working locally for me because I'm running a i386 container on a x86_64 kernel?

**Comment by dalcinl** [comment]
Update: I just ran the spawn tests on armel, and everything seems to be OK. As in this case I'm sure the container is running under emulation via qemu, my previous concern about i386 container on a x86_64 kernel is gone.

**Comment by dalcinl** [comment]
@drew-parsons I've updated the patch I pasted above to use `platform.architecture(None)`, see 13e8af69264917af5d260c0d5deabab76e5e4a4c.

**Comment by drew-parsons** [comment]
That should work well for me (linux).

Note the platform [documentation](https://docs.python.org/3.12/library/platform.html) suggests `architecture(...)` could be misleading on MacOS where executables may contain multiple architectures (the doc doesn't explain how it handles `executable=None`)

**Comment by dalcinl** [comment]
> Note the platform [documentation](https://docs.python.org/3.12/library/platform.html) suggests `architecture(...)` could be misleading on MacOS where executables may contain multiple architectures (the doc doesn't explain how it handles `executable=None`)

That's precisely the reason I'm passing `None`, this way the executable is not used at all, which is OK because I'm not interested in getting linkage but only bit-size of a pointer obtained from `struct.calcsize('P')` .

**Comment by drew-parsons** [comment]
That makes sense :)

**Comment by drew-parsons** [comment]
For what it's worth, test spawn still fails with`HYDRA_IFACE=lo HYDRA_LAUNCHER=fork`
```
[proxy:0@amdahl]     mcmd=spawn
nprocs=1
execname=/usr/bin/python3.12
totspawns=1
spawnssofar=1
argcnt=3
arg1=/tmp/autopkgtest.3T3mtL/tree/test/spawn_child.py
arg2=/tmp/autopkgtest.3T3mtL/tree/debian/python3-mpi4py/usr/lib/python3/dist-packages
arg3=
preput_num=1
preput_key_0=PARENT_ROOT_PORT_NAME
preput_val_0=tag#0$description#amdahl$port#58301$ifname#127.0.0.1$
info_num=0
endcmd
[proxy:0@amdahl] Sending upstream hdr.cmd = CMD_PMI
[proxy:0@amdahl] we don't understand this command, forwarding upstream
```

**Comment by dalcinl** [comment]
@hzhou Any idea what could be going on?

**Comment by hzhou** [comment]
The message looks okay. What was the failure?  A hang?

**Comment by hzhou** [comment]
I scrolled to earlier comments -- is this the spawn failure for powerpc? Does powerpc translate newlines in its libc? Because the spawn command contains newlines, I suspect maybe that is the cause. @drew-parsons, could you create an issue at https://github.com/pmodels/mpich/issues?

**Comment by drew-parsons** [comment]
It exits with error code 16.  There was other info, evidently I didn't copy the meaningful part. The end of the test output is
```
(sid_armel-dchroot)$ HYDRA_IFACE=lo HYDRA_LAUNCHER=fork PYTHONPATH=./debian/python3-mpi4py/usr/lib/python3/dist-packages autopkgtest -B -- null
...
testPutProcNull (test_rma_nb.TestRMAWorld.testPutProcNull) ... ok
testPutProcNull (test_rma_nb.TestRMAWorld.testPutProcNull) ... ok
testPutProcNull (test_rma_nb.TestRMAWorld.testPutProcNull) ... ok
testPutProcNull (test_rma_nb.TestRMAWorld.testPutProcNull) ... ok
testPutProcNull (test_rma_nb.TestRMAWorld.testPutProcNull) ... ok
ok
testArgsOnlyAtRoot (test_spawn.TestSpawnSelf.testArgsOnlyAtRoot) ... ok
testArgsOnlyAtRoot (test_spawn.TestSpawnSelf.testArgsOnlyAtRoot) ... ok
testArgsOnlyAtRoot (test_spawn.TestSpawnSelf.testArgsOnlyAtRoot) ... ok
testArgsOnlyAtRoot (test_spawn.TestSpawnSelf.testArgsOnlyAtRoot) ... testArgsOnlyAtRoot (test_spawn.TestSpawnSelf.testArgsOnlyAtRoot) ... [proxy:0@amdahl] Sending upstream hdr.cmd = CMD_STDERR
[proxy:0@amdahl] Sending upstream hdr.cmd = CMD_STDERR
[proxy:0@amdahl] Sending upstream hdr.cmd = CMD_STDERR
[proxy:0@amdahl] Sending upstream hdr.cmd = CMD_STDERR
[proxy:0@amdahl] Sending upstream hdr.cmd = CMD_STDERR
[proxy:0@amdahl] Sending upstream hdr.cmd = CMD_STDERR
[proxy:0@amdahl] we don't understand this command, forwarding upstream
[proxy:0@amdahl]     mcmd=spawn
nprocs=1
execname=/usr/bin/python3.12
totspawns=1
spawnssofar=1
argcnt=3
arg1=/tmp/autopkgtest.VaRWBv/tree/test/spawn_child.py
arg2=/tmp/autopkgtest.VaRWBv/tree/debian/python3-mpi4py/usr/lib/python3/dist-packages
arg3=
preput_num=1
preput_key_0=PARENT_ROOT_PORT_NAME
preput_val_0=tag#0$description#amdahl$port#57335$ifname#127.0.0.1$
info_num=0
endcmd
[proxy:0@amdahl] Sending upstream hdr.cmd = CMD_PMI
[proxy:0@amdahl] we don't understand this command, forwarding upstream
[proxy:0@amdahl]     mcmd=spawn
nprocs=1
execname=/usr/bin/python3.12
totspawns=1
spawnssofar=1
argcnt=3
arg1=/tmp/autopkgtest.VaRWBv/tree/test/spawn_child.py
arg2=/tmp/autopkgtest.VaRWBv/tree/debian/python3-mpi4py/usr/lib/python3/dist-packages
arg3=
preput_num=1
preput_key_0=PARENT_ROOT_PORT_NAME
preput_val_0=tag#0$description#amdahl$port#36665$ifname#127.0.0.1$
info_num=0
endcmd
[proxy:0@amdahl] Sending upstream hdr.cmd = CMD_PMI
[mpiexec@amdahl] [pgid: 0] got PMI command: mcmd=spawn
nprocs=1
execname=/usr/bin/python3.12
totspawns=1
spawnssofar=1
argcnt=3
arg1=/tmp/autopkgtest.VaRWBv/tree/test/spawn_child.py
arg2=/tmp/autopkgtest.VaRWBv/tree/debian/python3-mpi4py/usr/lib/python3/dist-packages
arg3=
preput_num=1
preput_key_0=PARENT_ROOT_PORT_NAME
preput_val_0=tag#0$description#amdahl$port#57335$ifname#127.0.0.1$
info_num=0
endcmd
[unset]: ERROR: Expecting value after arg3= in parse_v1_mcmd (202)
[unset]: ERROR: PMIU_cmd_parse (310)
[mpiexec@amdahl] handle_pmi_cmd (mpiexec/pmiserv_cb.c:57): unable to parse PMI command
[mpiexec@amdahl] control_cb (mpiexec/pmiserv_cb.c:367): unable to process PMI command
[mpiexec@amdahl] HYDT_dmxu_poll_wait_for_event (lib/tools/demux/demux_poll.c:76): callback returned error status
[mpiexec@amdahl] HYD_pmci_wait_for_completion (mpiexec/pmiserv_pmci.c:173): error waiting for event
[mpiexec@amdahl] main (mpiexec/mpiexec.c:260): process manager error waiting for completion
autopkgtest [16:29:04]: ERROR: testbed failure: testbed auxverb failed with exit code 255
(sid_armel-dchroot)$ echo $?
16
```

**Comment by hzhou** [comment]
Is this on powerpc only?

**Comment by drew-parsons** [comment]
This is armel (armv8l), not powerpc.

But all 32 bit arches (including [i386](https://buildd.debian.org/status/fetch.php?pkg=mpi4py&arch=i386&ver=3.1.6-7&stamp=1721234162&raw=0)) have been getting spawn failure.

**Comment by hzhou** [comment]
I see.

**Comment by hzhou** [comment]
@dalcinl Here is the culprit :
```
[unset]: ERROR: Expecting value after arg3= in parse_v1_mcmd (202)
```
Any reason you are providing an empty argument here?

**Comment by drew-parsons** [comment]
The mpich (or mpi4py) error code was actually 255 not 16. The debian test tool autopkgtest returns exit code 16 to acknowledge "testbed failure".

I've filedissue #7073 at mpich upstream

**Comment by drew-parsons** [comment]
My guess is the empty argument must be "no vt",
https://github.com/mpi4py/mpi4py/blob/19c63b4d0893cdd8d3d5bb494f19eb96ec335060/test/test_spawn.py#L90

We can see @dalcinl removed that in HEAD,
https://github.com/mpi4py/mpi4py/blob/13e8af69264917af5d260c0d5deabab76e5e4a4c/test/test_spawn.py#L108

**Comment by drew-parsons** [comment]
Garlic was applied to remove the vampires,
https://github.com/mpi4py/mpi4py/pull/129

**Comment by dalcinl** [comment]
Ok, so IMHO this looks like is a bug in MPICH's PMI?. And empty argument is valid argument, right?

```console
python -c 'import sys;print(sys.argv)' 0 '' 1 '' 2
['-c', '0', '', '1', '', '2']
```

**Comment by hzhou** [comment]
Well, not a bug, but a gap in PMI. The current PMI design doesn't allow
empty arguments. Please feel free to report issue. We'll see how to improve
in the future

**Comment by hzhou** [comment]
Well,  I take it back.  I guess we can take empty arguments.  The question
is,  is it more useful to accept empty arguments, or treat it as an error.
It is often an user error which user would appreciate to know rather than
to fail mysteriously later, right?

**Comment by dalcinl** [comment]
> It is often an user error which user would appreciate to know rather than to fail mysteriously later, right?

IMHO, it is up to the program consuming arguments how to treat an empty argument. An empty argument should be pass through, simply because it is not an error! Look at my example above how Python just accepts empty arguments and pass them down in `sys.argv`.

**Comment by dalcinl** [comment]
I personally use empty argument in PETSc-based applications. These empty arguments are usually related to filenames, and when empty, the semantics I assign is "use a default filename". There may be programs that need to accept empty strings as arguments, therefore PMI should not prevent that.

**Comment by drew-parsons** [comment]
Looks like that answers a question: I was starting to wonder whether this was a 32-bit problem at all. Debian uses openmpi on 64-bit systems, so I never checked these tests on 64-bit mpich.

**Comment by dalcinl** [comment]
Now that mpi4py skips pack/unpack external32 tests for `long double` on 32bit architectures, and that the spawn issue was identified with an upstream follow up, I'm closing this issue.
